//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Twerp.rc
//
#define IDS_APPNAME                     1
#define IDS_WINDOWTITLE                 2
#define IDS_BADDEST                     29
#define TW_APP_ACQUIRE                  100
#define TW_APP_ACQUIRE_TO_CLPB          101
#define TW_APP_SELECT_SOURCE            103
#define TW_APP_QUIT                     104
#define TW_APP_ABOUT                    105
#define TW_APP_SAVEAS                   106
#define TW_APP_BW                       107
#define TW_APP_GRAYSCALE                108
#define TW_APP_RGB                      109
#define TW_APP_PALETTE                  110
#define TW_APP_ANYPIX                   111
#define TW_APP_SHOWUI                   112
#define TW_APP_HIDEUI                   113
#define TW_APP_OPEN                     114
#define IDEZT_VER                       302
#define IDTWAIN_AVAIL                   303
#define IDS_ERR_DIB2DDB                 700
#define IDS_ERR_NOIMAGE                 701
#define IDS_EZT_VER                     702
#define IDS_TWAIN_PRESENT               703
#define IDS_NO_TWAIN                    704
#define IDS_ERR_WRITE                   705
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         116
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
